import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const presetsDir = path.resolve(__dirname, "../../../presets");
const outFile = path.resolve(__dirname, "../src/generated/preset-registry.ts");

// Discover all preset folders that contain a spec.json
const presetNames = fs
  .readdirSync(presetsDir, { withFileTypes: true })
  .filter((entry) => {
    if (!entry.isDirectory()) return false;
    return fs.existsSync(path.join(presetsDir, entry.name, "spec.json"));
  })
  .map((entry) => entry.name)
  .sort();

if (presetNames.length === 0) {
  console.warn("Warning: No presets found in presets/ directory.");
}

// Read each spec.json, strip $schema, and inline as JSON literals
const registrations = presetNames
  .map((name) => {
    const specPath = path.join(presetsDir, name, "spec.json");
    const spec = JSON.parse(fs.readFileSync(specPath, "utf-8"));
    delete spec["$schema"];
    return `registerPreset(${JSON.stringify(spec)});`;
  })
  .join("\n");

const source = `// This file is auto-generated by scripts/generate-preset-registry.ts
// Do not edit manually. Add new presets to the presets/ directory instead.
import { registerPreset } from "../preset-runner.js";

${registrations}
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, source, "utf-8");

console.log(
  `Generated preset registry with ${presetNames.length} preset(s): ${presetNames.join(", ")}`
);
